### ISSUE TITLE
Help me a little please

### ISSUE THREAD

**Issue by azapicoe** [jufkes/bittrexBot#6]
Hi man, Amazing job, im very excited with this, and thank you very much for developing this.. I have a little problem, when i run:

`docker run --name bittrexbot -v ~/.config:/opt/bittrexBot/config --restart always jufkes/bittrexbot:latest`

i get the following error:

`Traceback (most recent call last):
  File "bot.py", line 77, in <module>
    orderVolume = api.getbalance(currency)['Available'] + extCoinBalance
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
checking value
0.0011602`

Dont know what this means because im very newbie in crypto, linux, python etc... ¿Maybe i havent enought btc to start trading?
Thank you very much!!.. If this works you will probably recive some shatoshis from me :)

**Comment by jufkes** [comment]
Thanks! Sorry i didnt see this in my feed.

Couple questions:
* Do you currently have a balance for the token set you're wanting to trade? For example, if you're trying to trade gnt you need to have gnt to trade.
* Can you paste in the values / volumes you're trying to trade? DO NOT SHARE YOUR KEY :-D

The line in the bot.py that's complaining is calling out to Bittrex to retrieve the amount of the token you're trying to trade that's available to place an order so that it can determine how much to place.

I'll do some testing on it later today and see if i can duplicate you're response.

**Comment by jufkes** [comment]
I havent been able to duplicate this error...still trying though.

Would you be able to provide the bot configuration for the amounts (do not include your key and secret information)? What's your balance for btc and the token? What was the number 0.0011602?

**Comment by azapicoe** [comment]
Hey, thanks for the response. I cant test the bot right now because i have no BTC in my account, (all holding qtum until green bars appear). I checked the botConfig.json and this are the values:

{
  "apiKey": "xxxxxxxxxxxxxxxxxxx",
  "apiSecret": "xxxxxxxxxxxxx",
  "trade": "BTC",
  "currency": "WAVES",
  "sellValuePercent": 4,
  "buyValuePercent": 7,
  "sellVolumePercent": 3,
  "buyVolumePercent": 3,
  "extCoinBalance": 0,
  "checkInterval": 30
}

Hope my situation change soon and i can continue testing this, i really want to get it working. Also i will try to reset api keys to see if that is the problem, as use to be. Thanks!

**Comment by jufkes** [comment]
No worries and totally understand. Your values look right. I'm still unable to duplicate that error. 

When you ran it, what was the 0.0011602 from?

The only thing I can figure is that there may be an issue with balances that have less than 1 whole token and will attempt to do some testing in that regard.

**Comment by zemelax** [comment]
azapicoe , do you start the bot? can you hel me please?

**Comment by jufkes** [comment]
Closing due to lack of response.
